services:
  postgres:
    image: postgres:16-alpine
    container_name: ereader
    restart: no
    environment:
      POSTGRES_USER: ereader
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: ereader
    ports:
      - "5432:5432"
    volumes:
      - ereader_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: ereader-redis
    restart: no
    ports:
      - "6379:6379"
    volumes:
      - ereader_redis:/data
    command: ["redis-server", "--appendonly", "yes"]

  ereader-minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    restart: no
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"   # Admin UI at http://localhost:9001
    volumes:
      - ereader_minio_data:/data

volumes:
  ereader_data:
  ereader_redis:
  ereader_minio_data:
